/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bj.vista.playing;

import bj.game.Player;
import bj.util.Card;
import bj.util.Deck;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author alvaro
 */
public class PlayingWindow extends javax.swing.JFrame implements Runnable {

    private Deck baraja;
    private ArrayList<Player> mesa;
    private ArrayList<JLabel> playerlabel; 
    private Player p1, p2, p3, p4, p5;
    int xPanel, yPanel;
    boolean reparte = false;
    Thread hilo;
    
    /**
     * Creates new form PlayingWindow
     */
    public PlayingWindow() {
        
        initComponents();
        
        baraja = new Deck();
        mesa = new ArrayList<Player>();
        playerlabel = new ArrayList<JLabel>();  
        p1 = new Player("player1", 1);     mesa.add(p1);  playerlabel.add(jLabel5);
        p2 = new Player("player2", 2);     mesa.add(p2);  playerlabel.add(jLabel4);
        p3 = new Player("Eustaquio", 3);   mesa.add(p3);  playerlabel.add(jLabel3);
        p4 = new Player("player4", 4);     mesa.add(p4);  playerlabel.add(jLabel2);
        p5 = new Player("player5", 5);     mesa.add(p5);  playerlabel.add(jLabel1);
        
        for(int i = 0; i<5; i++) playerlabel.get(i).setText(mesa.get(i).getName());
       
        //hilo.start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMesa = new javax.swing.JPanel();
        panelCroupier = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        botonLimpia = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        botonReparte = new javax.swing.JButton();
        panelPlayer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        infoP5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        infoP4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        infoP3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        infoP2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        infoP1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlackJackva - @Velastroll");
        setBackground(new java.awt.Color(29, 82, 38));

        panelMesa.setBackground(new java.awt.Color(12, 80, 11));
        panelMesa.setPreferredSize(new java.awt.Dimension(350, 200));

        javax.swing.GroupLayout panelMesaLayout = new javax.swing.GroupLayout(panelMesa);
        panelMesa.setLayout(panelMesaLayout);
        panelMesaLayout.setHorizontalGroup(
            panelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        panelMesaLayout.setVerticalGroup(
            panelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(panelMesa, java.awt.BorderLayout.CENTER);

        panelCroupier.setBackground(new java.awt.Color(12, 110, 10));

        jPanel7.setBackground(new java.awt.Color(12, 80, 11));
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 0));

        botonLimpia.setText("LIMPIAR");
        botonLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiaActionPerformed(evt);
            }
        });
        jPanel7.add(botonLimpia);

        jPanel8.setBackground(new java.awt.Color(12, 80, 11));
        jPanel8.setPreferredSize(new java.awt.Dimension(559, 100));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(12, 80, 11));
        jPanel13.setPreferredSize(new java.awt.Dimension(150, 0));

        botonReparte.setText("REPARTE");
        botonReparte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReparteActionPerformed(evt);
            }
        });
        jPanel13.add(botonReparte);

        javax.swing.GroupLayout panelCroupierLayout = new javax.swing.GroupLayout(panelCroupier);
        panelCroupier.setLayout(panelCroupierLayout);
        panelCroupierLayout.setHorizontalGroup(
            panelCroupierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCroupierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCroupierLayout.setVerticalGroup(
            panelCroupierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCroupierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCroupierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelCroupier, java.awt.BorderLayout.PAGE_START);

        panelPlayer.setBackground(new java.awt.Color(12, 80, 11));
        panelPlayer.setPreferredSize(new java.awt.Dimension(550, 116));
        panelPlayer.setLayout(new java.awt.GridLayout());

        jPanel2.setBackground(new java.awt.Color(12, 110, 10));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 90));

        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("player5");

        infoP5.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP5.setForeground(new java.awt.Color(254, 254, 254));
        infoP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP5.setText("$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoP5)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelPlayer.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(12, 110, 10));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 90));
        jPanel4.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("player4");

        infoP4.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP4.setForeground(new java.awt.Color(254, 254, 254));
        infoP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP4.setText("$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoP4)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelPlayer.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(12, 110, 10));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 90));

        jLabel3.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("player3");

        infoP3.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP3.setForeground(new java.awt.Color(254, 254, 254));
        infoP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP3.setText("$");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoP3)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelPlayer.add(jPanel6);

        jPanel10.setBackground(new java.awt.Color(12, 110, 10));
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 90));

        jLabel4.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("player2");

        infoP2.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP2.setForeground(new java.awt.Color(254, 254, 254));
        infoP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP2.setText("$");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoP2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelPlayer.add(jPanel10);

        jPanel12.setBackground(new java.awt.Color(12, 110, 10));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 90));

        jLabel5.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("player1");

        infoP1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP1.setForeground(new java.awt.Color(254, 254, 254));
        infoP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP1.setText("$");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoP1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelPlayer.add(jPanel12);

        getContentPane().add(panelPlayer, java.awt.BorderLayout.SOUTH);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonReparteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReparteActionPerformed
        
        xPanel = this.panelMesa.getWidth();
        yPanel = this.panelMesa.getHeight();       
        hilo = new Thread(this);
        hilo.start();
        reparte=true;

    }//GEN-LAST:event_botonReparteActionPerformed

    private void botonLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiaActionPerformed
        rebootPlayers();
        limpiaMesa();
        baraja = new Deck();
        actualizaValor();
        actualizaStatus();
    }//GEN-LAST:event_botonLimpiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayingWindow().setVisible(true);
            }
        });
    }
    
    public void reparteCartas(){
        for (Player p: mesa){
            if (p.getStatus()){
                p.addCard(baraja.getCard());            
                actualizaValor();
            }
        } 
    }
    
    private void actualizaStatus(){
        
        if(p1.getPoints()==21) infoP1.setForeground(Color.YELLOW);
        else if (!p1.getStatus()) infoP1.setForeground(Color.RED);
        else infoP1.setForeground(Color.WHITE);
        
        if(p2.getPoints()==21) infoP2.setForeground(Color.YELLOW);
        else if (!p2.getStatus()) infoP2.setForeground(Color.RED);
        else infoP2.setForeground(Color.WHITE);
        
        if(p3.getPoints()==21) infoP3.setForeground(Color.YELLOW);
        else if (!p3.getStatus()) infoP3.setForeground(Color.RED);
        else infoP3.setForeground(Color.WHITE);
        
        if(p4.getPoints()==21) infoP4.setForeground(Color.YELLOW);
        else if (!p4.getStatus()) infoP4.setForeground(Color.RED);
        else infoP4.setForeground(Color.WHITE);
        
        if(p5.getPoints()==21) infoP5.setForeground(Color.YELLOW);
        else if (!p5.getStatus()) infoP5.setForeground(Color.RED);
        else infoP5.setForeground(Color.WHITE);
    }
       
    private void actualizaValor(){
        infoP1.setText("Puntos: "+ p1.getPoints());
        infoP2.setText("Puntos: "+ p2.getPoints());
        infoP3.setText("Puntos: "+ p3.getPoints());
        infoP4.setText("Puntos: "+ p4.getPoints());
        infoP5.setText("Puntos: "+ p5.getPoints());
        
    }
    
    public void imprimeCartas(){
        ArrayList<Card> cartas;
        for(Player p: mesa){
            if (p.getStatus()){
                cartas = p.getHand().getHand();
                Card c = cartas.get(cartas.size()-1); 
                c.setBounds(xPanel/2, 0);
                movimientoCarta(p, c, cartas.size());
            }
        }
    }
    
    private void movimientoCarta(Player p, Card c, int round){
        
        panelMesa.add(c);
        int x0 = c.getLocation().x;
        int y0 = c.getLocation().y;
        int hueco = xPanel/5;
        int xFinal = (xPanel - (p.getNumber() - 1)*(xPanel/5) - 45);
        int yFinal = (yPanel - 50*round);
        int y;
        int x = x0;
        if (xFinal>x0){
            while(x<=xFinal){
                y = y0 + (x - x0)*(yFinal - y0)/(xFinal-x0);
                c.setBounds(x, y);
                x++;
                try{hilo.sleep(1);}
                catch(Exception ex){}
            }
        } else {
            while(x>=xFinal){
                y = y0 + (x - x0)*(yFinal - y0)/(xFinal-x0);
                c.setBounds(x, y);
                x--;  
                try{hilo.sleep(1);}
                catch(Exception ex){}
            }
        }
        c.setImagen(c.getCard());
        p.updateSatus();
    }

    private void limpiaMesa(){
        panelMesa.removeAll();
        repaint();
    }

    private void rebootPlayers(){
        p1.reboot();
        p2.reboot();
        p3.reboot();
        p4.reboot();
        p5.reboot();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLimpia;
    private javax.swing.JButton botonReparte;
    private javax.swing.JLabel infoP1;
    private javax.swing.JLabel infoP2;
    private javax.swing.JLabel infoP3;
    private javax.swing.JLabel infoP4;
    private javax.swing.JLabel infoP5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel panelCroupier;
    private javax.swing.JPanel panelMesa;
    private javax.swing.JPanel panelPlayer;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void run(){
        
        while(hilo.isAlive()){ // Se ejecuta cuando el hilo esta en funcionamiento.
            
            
            while(reparte){
                reparteCartas();
                imprimeCartas();
                actualizaStatus();
                reparte=false;
                hilo.stop();
            }
        }
    }
}
