/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bj.vista.playing;

import bj.game.Player;
import bj.util.Card;
import bj.util.Deck;
import bj.util.Hand;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author alvaro
 */
public class PlayingWindow extends javax.swing.JFrame {

    
    private Deck baraja;
    private ArrayList<Player> mesa;
    private ArrayList<JLabel> playerlabel;
    private Player p1;
    private Player p2;
    private Player p3;
    private Player p4;
    private Player p5;
    
    /**
     * Creates new form PlayingWindow
     */
    public PlayingWindow() {
        
        initComponents();
        
        baraja = new Deck();
        mesa = new ArrayList<Player>();
        playerlabel = new ArrayList<JLabel>();
        
        p1 = new Player("player1");  mesa.add(p1);  playerlabel.add(jLabel5);
        p2 = new Player("player2");  mesa.add(p2);  playerlabel.add(jLabel4);
        p3 = new Player("Eustaquio");  mesa.add(p3);  playerlabel.add(jLabel3);
        p4 = new Player("player4");  mesa.add(p4);  playerlabel.add(jLabel2);
        p5 = new Player("player5");  mesa.add(p5);  playerlabel.add(jLabel1);
        
        for(int i = 0; i<5; i++) playerlabel.get(i).setText(mesa.get(i).getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMesa = new javax.swing.JPanel();
        panelCroupier = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panelPlayer = new javax.swing.JPanel();
        panelPlayer5 = new javax.swing.JPanel();
        mesaPlayer5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        infoP5 = new javax.swing.JLabel();
        panelPlayer4 = new javax.swing.JPanel();
        mesaPlayer4 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        infoP4 = new javax.swing.JLabel();
        panelPlayer3 = new javax.swing.JPanel();
        mesaPlayer3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        infoP3 = new javax.swing.JLabel();
        panelPlayer2 = new javax.swing.JPanel();
        mesaPlayer2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        infoP2 = new javax.swing.JLabel();
        panelPlayer1 = new javax.swing.JPanel();
        mesaPlayer1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        infoP1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(29, 82, 38));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelMesa.setBackground(new java.awt.Color(178, 218, 187));

        panelCroupier.setBackground(new java.awt.Color(12, 110, 10));

        jPanel7.setBackground(new java.awt.Color(12, 80, 11));
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 0));

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(12, 80, 11));
        jPanel8.setPreferredSize(new java.awt.Dimension(559, 100));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(12, 80, 11));
        jPanel13.setPreferredSize(new java.awt.Dimension(150, 0));

        jButton1.setText("REPARTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCroupierLayout = new javax.swing.GroupLayout(panelCroupier);
        panelCroupier.setLayout(panelCroupierLayout);
        panelCroupierLayout.setHorizontalGroup(
            panelCroupierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCroupierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCroupierLayout.setVerticalGroup(
            panelCroupierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCroupierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCroupierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelPlayer.setLayout(new javax.swing.BoxLayout(panelPlayer, javax.swing.BoxLayout.LINE_AXIS));

        panelPlayer5.setBackground(new java.awt.Color(255, 142, 0));

        mesaPlayer5.setBackground(new java.awt.Color(12, 110, 10));
        mesaPlayer5.setLayout(new java.awt.GridLayout(4, 2));

        jPanel2.setBackground(new java.awt.Color(12, 110, 10));

        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("player5");

        infoP5.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP5.setForeground(new java.awt.Color(254, 254, 254));
        infoP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP5.setText("$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(infoP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoP5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPlayer5Layout = new javax.swing.GroupLayout(panelPlayer5);
        panelPlayer5.setLayout(panelPlayer5Layout);
        panelPlayer5Layout.setHorizontalGroup(
            panelPlayer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mesaPlayer5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPlayer5Layout.setVerticalGroup(
            panelPlayer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer5Layout.createSequentialGroup()
                .addComponent(mesaPlayer5, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPlayer.add(panelPlayer5);

        panelPlayer4.setBackground(new java.awt.Color(146, 255, 0));

        mesaPlayer4.setBackground(new java.awt.Color(12, 110, 10));
        mesaPlayer4.setLayout(new java.awt.GridLayout(4, 2));

        jPanel4.setBackground(new java.awt.Color(12, 110, 10));

        jLabel2.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("player4");

        infoP4.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP4.setForeground(new java.awt.Color(254, 254, 254));
        infoP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP4.setText("$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(infoP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoP4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPlayer4Layout = new javax.swing.GroupLayout(panelPlayer4);
        panelPlayer4.setLayout(panelPlayer4Layout);
        panelPlayer4Layout.setHorizontalGroup(
            panelPlayer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mesaPlayer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPlayer4Layout.setVerticalGroup(
            panelPlayer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer4Layout.createSequentialGroup()
                .addComponent(mesaPlayer4, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPlayer.add(panelPlayer4);

        panelPlayer3.setBackground(new java.awt.Color(9, 254, 240));

        mesaPlayer3.setBackground(new java.awt.Color(12, 110, 10));
        mesaPlayer3.setLayout(new java.awt.GridLayout(4, 2));

        jPanel6.setBackground(new java.awt.Color(12, 110, 10));

        jLabel3.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("player3");

        infoP3.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP3.setForeground(new java.awt.Color(254, 254, 254));
        infoP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP3.setText("$");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(infoP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoP3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPlayer3Layout = new javax.swing.GroupLayout(panelPlayer3);
        panelPlayer3.setLayout(panelPlayer3Layout);
        panelPlayer3Layout.setHorizontalGroup(
            panelPlayer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mesaPlayer3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPlayer3Layout.setVerticalGroup(
            panelPlayer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer3Layout.createSequentialGroup()
                .addComponent(mesaPlayer3, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPlayer.add(panelPlayer3);

        panelPlayer2.setBackground(new java.awt.Color(253, 43, 222));

        mesaPlayer2.setBackground(new java.awt.Color(12, 110, 10));
        mesaPlayer2.setLayout(new java.awt.GridLayout(4, 2));

        jPanel10.setBackground(new java.awt.Color(12, 110, 10));

        jLabel4.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("player2");

        infoP2.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP2.setForeground(new java.awt.Color(254, 254, 254));
        infoP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP2.setText("$");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(infoP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoP2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPlayer2Layout = new javax.swing.GroupLayout(panelPlayer2);
        panelPlayer2.setLayout(panelPlayer2Layout);
        panelPlayer2Layout.setHorizontalGroup(
            panelPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mesaPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPlayer2Layout.setVerticalGroup(
            panelPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer2Layout.createSequentialGroup()
                .addComponent(mesaPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPlayer.add(panelPlayer2);

        panelPlayer1.setBackground(new java.awt.Color(11, 13, 195));

        mesaPlayer1.setBackground(new java.awt.Color(12, 110, 10));
        mesaPlayer1.setLayout(new java.awt.GridLayout(4, 2));

        jPanel12.setBackground(new java.awt.Color(12, 110, 10));

        jLabel5.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("player1");

        infoP1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        infoP1.setForeground(new java.awt.Color(254, 254, 254));
        infoP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoP1.setText("$");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(infoP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoP1)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPlayer1Layout = new javax.swing.GroupLayout(panelPlayer1);
        panelPlayer1.setLayout(panelPlayer1Layout);
        panelPlayer1Layout.setHorizontalGroup(
            panelPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mesaPlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPlayer1Layout.setVerticalGroup(
            panelPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer1Layout.createSequentialGroup()
                .addComponent(mesaPlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPlayer.add(panelPlayer1);

        javax.swing.GroupLayout panelMesaLayout = new javax.swing.GroupLayout(panelMesa);
        panelMesa.setLayout(panelMesaLayout);
        panelMesaLayout.setHorizontalGroup(
            panelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCroupier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        panelMesaLayout.setVerticalGroup(
            panelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMesaLayout.createSequentialGroup()
                .addComponent(panelCroupier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );

        getContentPane().add(panelMesa, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reparteCartas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        rebootPlayers();
        limpiaMesas();
        baraja = new Deck();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayingWindow().setVisible(true);
            }
        });
    }
    
    public void reparteCartas(){
        for (Player p: mesa){
            if (p.getStatus()){
                p.addCard(baraja.getCard());
                limpiaMesas();
                imprimeCartas();
                actualizaValor();
            }
        }
        actualizaStatus(); 
    }
    
    private void actualizaStatus(){
        if (!p1.getStatus()) infoP1.setForeground(Color.RED);
        else infoP1.setForeground(Color.WHITE);
        if (!p2.getStatus()) infoP2.setForeground(Color.RED);
        else infoP2.setForeground(Color.WHITE);
        if (!p3.getStatus()) infoP3.setForeground(Color.RED);
        else infoP3.setForeground(Color.WHITE);
        if (!p4.getStatus()) infoP4.setForeground(Color.RED);
        else infoP4.setForeground(Color.WHITE);
        if (!p5.getStatus()) infoP5.setForeground(Color.RED);
        else infoP5.setForeground(Color.WHITE);
    }
    
    
    private void actualizaValor(){
        infoP1.setText("Puntos: "+ p1.getPoints());
        infoP2.setText("Puntos: "+ p2.getPoints());
        infoP3.setText("Puntos: "+ p3.getPoints());
        infoP4.setText("Puntos: "+ p4.getPoints());
        infoP5.setText("Puntos: "+ p5.getPoints());
    }
    
    public void imprimeCartas(){
        ArrayList<Card> cartas;
        //limpiaMesas();
        cartas = p1.getHand().getHand();
        for (Card c: cartas){
            String url = "/images/card/"+c.getCard()+".png";
            System.out.println("Intento de url: "+ url);
            mesaPlayer1.add(new javax.swing.JButton(new javax.swing.ImageIcon(getClass().getResource(url))));
        }
        cartas = p2.getHand().getHand();
        for (Card c: cartas)
            mesaPlayer2.add(new javax.swing.JButton(new javax.swing.ImageIcon(getClass().getResource("/images/card/"+c.getCard()+".png"))));
        
        cartas = p3.getHand().getHand();
        for (Card c: cartas)
            mesaPlayer3.add(new javax.swing.JButton(new javax.swing.ImageIcon(getClass().getResource("/images/card/"+c.getCard()+".png"))));
        
        cartas = p4.getHand().getHand();
        for (Card c: cartas)
            mesaPlayer4.add(new javax.swing.JButton(new javax.swing.ImageIcon(getClass().getResource("/images/card/"+c.getCard()+".png"))));
        
        cartas = p5.getHand().getHand();
        for (Card c: cartas)
            mesaPlayer5.add(new javax.swing.JButton(new javax.swing.ImageIcon(getClass().getResource("/images/card/"+c.getCard()+".png"))));
    }
    
    private void limpiaMesas(){
        mesaPlayer1.removeAll();
        mesaPlayer2.removeAll();
        mesaPlayer3.removeAll();
        mesaPlayer4.removeAll();
        mesaPlayer5.removeAll();
        repaint();
    }

    private void rebootPlayers(){
        p1.reboot();
        p2.reboot();
        p3.reboot();
        p4.reboot();
        p5.reboot();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoP1;
    private javax.swing.JLabel infoP2;
    private javax.swing.JLabel infoP3;
    private javax.swing.JLabel infoP4;
    private javax.swing.JLabel infoP5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel mesaPlayer1;
    private javax.swing.JPanel mesaPlayer2;
    private javax.swing.JPanel mesaPlayer3;
    private javax.swing.JPanel mesaPlayer4;
    private javax.swing.JPanel mesaPlayer5;
    private javax.swing.JPanel panelCroupier;
    private javax.swing.JPanel panelMesa;
    private javax.swing.JPanel panelPlayer;
    private javax.swing.JPanel panelPlayer1;
    private javax.swing.JPanel panelPlayer2;
    private javax.swing.JPanel panelPlayer3;
    private javax.swing.JPanel panelPlayer4;
    private javax.swing.JPanel panelPlayer5;
    // End of variables declaration//GEN-END:variables
}
